apiVersion: v1
kind: Service
metadata:
  name: airequest-service
  labels:
    app: airequest-app
spec:
  type: NodePort
  selector:
    app: airequest-app
  ports:
    - name: http
      nodePort: 30003
      port: 9092
      targetPort: 9092
      protocol: TCP